// คลังหัวข้อสำหรับฝึกพูด: en = หัวข้อ, th = คำแปล, hints = คำถามช่วยคิดว่าจะพูดอะไร
const TOPICS = [
  // Daily life
  { cat: "daily", en: "Describe your morning routine.", th: "เล่ากิจวัตรตอนเช้าของคุณ",
    hints: ["What time do you wake up?", "What do you eat for breakfast?", "How do you get to work or school?"] },
  { cat: "daily", en: "Talk about your best friend.", th: "พูดถึงเพื่อนสนิทของคุณ",
    hints: ["How did you meet?", "What is he or she like?", "What do you do together?"] },
  { cat: "daily", en: "Describe your home.", th: "อธิบายบ้านของคุณ",
    hints: ["Where is it?", "How many rooms are there?", "What is your favorite room?"] },
  { cat: "daily", en: "What did you do last weekend?", th: "สุดสัปดาห์ที่แล้วคุณทำอะไร",
    hints: ["Where did you go?", "Who were you with?", "Did you enjoy it? Why?"] },
  { cat: "daily", en: "Talk about your family.", th: "พูดถึงครอบครัวของคุณ",
    hints: ["How many people are in your family?", "What do they do?", "What do you do together?"] },
  { cat: "daily", en: "Describe your neighborhood.", th: "อธิบายละแวกบ้านของคุณ",
    hints: ["What places are near your home?", "Is it quiet or busy?", "What would you change?"] },
  { cat: "daily", en: "How do you usually relax after a long day?", th: "ปกติคุณพักผ่อนอย่างไรหลังวันที่เหนื่อย",
    hints: ["What do you do first when you get home?", "Do you prefer to be alone or with others?", "Why does it help you relax?"] },

  // Hobbies
  { cat: "hobby", en: "What is your favorite hobby?", th: "งานอดิเรกที่คุณชอบที่สุดคืออะไร",
    hints: ["When did you start?", "How often do you do it?", "Why do you like it?"] },
  { cat: "hobby", en: "Talk about a movie you like.", th: "พูดถึงหนังที่คุณชอบ",
    hints: ["What is the story about?", "Who is your favorite character?", "Would you recommend it?"] },
  { cat: "hobby", en: "Describe your favorite song or singer.", th: "พูดถึงเพลงหรือนักร้องที่คุณชอบ",
    hints: ["When do you listen to it?", "How does it make you feel?", "When did you first hear it?"] },
  { cat: "hobby", en: "Do you like sports? Why or why not?", th: "คุณชอบกีฬาไหม เพราะอะไร",
    hints: ["Which sports do you play or watch?", "Who do you play with?", "Is exercise important to you?"] },
  { cat: "hobby", en: "Talk about a book or story you remember.", th: "พูดถึงหนังสือหรือเรื่องเล่าที่คุณจำได้",
    hints: ["What happens in it?", "When did you read it?", "What did you learn from it?"] },
  { cat: "hobby", en: "What would you like to learn in the future?", th: "อนาคตคุณอยากเรียนรู้อะไร",
    hints: ["Why does it interest you?", "How would you learn it?", "How would it change your life?"] },
  { cat: "hobby", en: "Describe a game you enjoy playing.", th: "พูดถึงเกมที่คุณชอบเล่น",
    hints: ["How do you play it?", "Who do you play with?", "Why is it fun?"] },

  // Travel
  { cat: "travel", en: "Describe a place you want to visit.", th: "พูดถึงสถานที่ที่คุณอยากไปเที่ยว",
    hints: ["Where is it?", "What do you want to do there?", "Who would you go with?"] },
  { cat: "travel", en: "Talk about your best trip.", th: "เล่าถึงทริปที่ดีที่สุดของคุณ",
    hints: ["Where did you go?", "What did you see and eat?", "What was the most memorable moment?"] },
  { cat: "travel", en: "Do you prefer the beach or the mountains?", th: "คุณชอบทะเลหรือภูเขามากกว่า",
    hints: ["What do you like about it?", "When did you last go there?", "What do you do there?"] },
  { cat: "travel", en: "Recommend a place in Thailand to a foreign tourist.", th: "แนะนำสถานที่ในไทยให้นักท่องเที่ยวต่างชาติ",
    hints: ["Why is it special?", "What can they do there?", "What is the best time to go?"] },
  { cat: "travel", en: "Do you like traveling alone or with others?", th: "คุณชอบเที่ยวคนเดียวหรือไปกับคนอื่น",
    hints: ["What are the good points?", "What are the bad points?", "Tell a short story from a trip."] },
  { cat: "travel", en: "Describe your hometown.", th: "อธิบายบ้านเกิดของคุณ",
    hints: ["Where is it?", "What is it famous for?", "What do you miss about it?"] },

  // Food
  { cat: "food", en: "What is your favorite food?", th: "อาหารที่คุณชอบที่สุดคืออะไร",
    hints: ["What does it taste like?", "Where do you eat it?", "How often do you eat it?"] },
  { cat: "food", en: "Explain how to cook a simple dish.", th: "อธิบายวิธีทำอาหารง่าย ๆ สักเมนู",
    hints: ["What ingredients do you need?", "What is the first step?", "Use words like first, then, finally."] },
  { cat: "food", en: "Do you prefer eating at home or eating out?", th: "คุณชอบกินข้าวที่บ้านหรือกินข้างนอก",
    hints: ["Which is cheaper?", "Which is healthier?", "What is your favorite restaurant?"] },
  { cat: "food", en: "Introduce a Thai dish to a foreigner.", th: "แนะนำอาหารไทยให้ชาวต่างชาติรู้จัก",
    hints: ["What is in it?", "Is it spicy, sweet, or sour?", "Where can they try it?"] },
  { cat: "food", en: "Talk about street food.", th: "พูดถึงอาหารริมทาง (สตรีทฟู้ด)",
    hints: ["What street food do you like?", "Why is it popular?", "Is it healthy?"] },
  { cat: "food", en: "Coffee or tea? Explain your choice.", th: "กาแฟหรือชา อธิบายว่าทำไมเลือกแบบนั้น",
    hints: ["When do you drink it?", "How do you like it?", "How many cups a day?"] },

  // Work & School
  { cat: "work", en: "Describe your job or your studies.", th: "อธิบายงานหรือการเรียนของคุณ",
    hints: ["What do you do every day?", "What do you like about it?", "What is difficult?"] },
  { cat: "work", en: "What is your dream job?", th: "งานในฝันของคุณคืออะไร",
    hints: ["Why do you want it?", "What skills do you need?", "What would a normal day look like?"] },
  { cat: "work", en: "Talk about a teacher who inspired you.", th: "พูดถึงครูที่สร้างแรงบันดาลใจให้คุณ",
    hints: ["What subject did they teach?", "What made them special?", "What did you learn from them?"] },
  { cat: "work", en: "Why do you want to improve your English?", th: "ทำไมคุณถึงอยากพัฒนาภาษาอังกฤษ",
    hints: ["How will it help your work or life?", "What is hardest for you?", "How do you practice?"] },
  { cat: "work", en: "Do you prefer working from home or at the office?", th: "คุณชอบทำงานที่บ้านหรือที่ออฟฟิศ",
    hints: ["What are the advantages?", "What are the disadvantages?", "What is your ideal setup?"] },
  { cat: "work", en: "Describe a challenge you solved.", th: "เล่าถึงปัญหาที่คุณเคยแก้ได้",
    hints: ["What was the problem?", "What did you do?", "What did you learn?"] },

  // Opinions
  { cat: "opinion", en: "Are smartphones good or bad for us?", th: "สมาร์ตโฟนดีหรือไม่ดีต่อเรา",
    hints: ["Give one good point.", "Give one bad point.", "What is your final opinion?"] },
  { cat: "opinion", en: "Is it better to live in the city or the countryside?", th: "อยู่ในเมืองหรือต่างจังหวัดดีกว่ากัน",
    hints: ["Think about jobs and transport.", "Think about nature and noise.", "Where would you choose to live?"] },
  { cat: "opinion", en: "Should students wear school uniforms?", th: "นักเรียนควรใส่ชุดนักเรียนไหม",
    hints: ["What are the reasons for?", "What are the reasons against?", "What do you think?"] },
  { cat: "opinion", en: "What makes a person happy?", th: "อะไรทำให้คนเรามีความสุข",
    hints: ["Is money important?", "What about family and friends?", "What makes you happy?"] },
  { cat: "opinion", en: "Is social media helpful or harmful?", th: "โซเชียลมีเดียมีประโยชน์หรือโทษ",
    hints: ["How do you use it?", "What problems can it cause?", "How can we use it well?"] },
  { cat: "opinion", en: "What is the most important invention?", th: "สิ่งประดิษฐ์ที่สำคัญที่สุดคืออะไร",
    hints: ["Why is it important?", "How would life be without it?", "Who uses it?"] },
  { cat: "opinion", en: "How can we protect the environment?", th: "เราจะช่วยปกป้องสิ่งแวดล้อมได้อย่างไร",
    hints: ["What can one person do?", "What should the government do?", "What do you already do?"] },
];

const CATEGORIES = [
  { id: "all", label: "ทั้งหมด" },
  { id: "daily", label: "ชีวิตประจำวัน" },
  { id: "hobby", label: "งานอดิเรก" },
  { id: "travel", label: "ท่องเที่ยว" },
  { id: "food", label: "อาหาร" },
  { id: "work", label: "งาน/การเรียน" },
  { id: "opinion", label: "แสดงความเห็น" },
];
